//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "js_worker")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub description: Option<String>,
    pub js_script: String,
    pub js_byte_code: Option<Vec<u8>>,
    pub route_name: Option<String>,
    pub env: Option<Json>,
    pub runtime_clean_time: Option<i64>,
    /// 单次执行总时长硬上限（ms）。NULL 时应用层兜底为 `DEFAULT_MAX_RUN_TIME_MS`（`30_000`）。
    pub max_run_time: Option<i64>,
    /// `QuickJS` C 栈上限（bytes）。NULL 时应用层兜底为 `DEFAULT_MAX_STACK_SIZE_BYTES`（1 MiB）。
    pub max_stack_size: Option<i64>,
    /// `QuickJS` 堆内存上限（bytes）。NULL 时应用层兜底为 `DEFAULT_MAX_HEAP_SIZE_BYTES`（8 MiB）。
    pub max_heap_size: Option<i64>,
    pub create_at: i64,
    pub update_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
