//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid: Uuid,
    pub token: String,
    pub cron_source: Option<String>,
    pub timestamp: Option<i64>,
    pub success: Option<bool>,
    pub error_message: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub task_event_type: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub task_event_result: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
