//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dynamic_monitoring")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid: Uuid,
    pub timestamp: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub cpu_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub ram_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub load_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub system_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub disk_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub network_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub gpu_data: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
