//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod crontab;
pub mod crontab_result;
pub mod dynamic_monitoring;
pub mod metadata;
pub mod static_monitoring;
pub mod task;
pub mod token;
