//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "static_monitoring")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid_id: i16,
    pub timestamp: i64,
    pub storage_time: Option<i64>,
    #[sea_orm(column_type = "JsonBinary")]
    pub cpu_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub system_data: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub gpu_data: Json,
    pub data_hash: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
