use log::{error, warn};
use rand::distr::Alphanumeric;
use rand::{Rng, rng};

#[cfg(feature = "for-server")]
use serde::Serialize;
#[cfg(feature = "for-server")]
use serde_json::{Map, Value};

#[cfg(feature = "for-server")]
pub mod error_message;

pub mod version;

// 毫秒时间戳，超过 u64 范围时返回 0
#[must_use]
pub fn get_local_timestamp_ms() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};

    let duration = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(std::time::Duration::ZERO);
    let millis = duration.as_millis();
    u64::try_from(millis).unwrap_or(0)
}

pub fn generate_random_string(len: usize) -> String {
    rng()
        .sample_iter(&Alphanumeric)
        .take(len)
        .map(char::from)
        .collect()
}

// Windows / MacOS / Linux 下的唯一 UUID 生成器，在同一系统下不变
#[must_use]
pub fn get_stable_device_uuid() -> uuid::Uuid {
    use uuid::Uuid;
    let mut machine_id = machine_uid::get().unwrap_or_else(|e| {
        error!("无法获取系统 ID: {e}, 使用 fallback");
        "fallback-device-id".to_string()
    });

    if cfg!(feature = "for-agent") {
        machine_id.push_str("-agent");
    } else {
        machine_id.push_str("-server");
    }

    Uuid::new_v5(&Uuid::NAMESPACE_OID, machine_id.as_bytes())
}

#[must_use]
pub fn compare_uuid(set_uuid: uuid::Uuid) -> bool {
    let stable_uuid = get_stable_device_uuid();
    if set_uuid == stable_uuid {
        true
    } else {
        warn!(
            "The `uuid` [{set_uuid}] configured in profile does not match the uuid [{stable_uuid}] generated by the environment."
        );
        warn!("This may result in undefined bahavior.");
        warn!("Modify the UUID with caution!");
        false
    }
}

#[cfg(feature = "for-server")]
use serde_json::value::RawValue;

// 直接序列化为 RawValue，避免 Value 树
#[cfg(feature = "for-server")]
pub fn to_raw_json<T: Serialize>(val: T) -> Box<RawValue> {
    serde_json::value::to_raw_value(&val).unwrap_or_else(|e| {
        error!("Serialization error: {e}");
        // fallback
        serde_json::value::to_raw_value(&serde_json::json!({
            "error_id": 101,
            "error_message": format!("Serialization error: {e}")
        }))
        .unwrap()
    })
}

#[cfg(feature = "for-server")]
pub fn try_parse_json_field(map: &mut Map<String, Value>, key: &str) {
    if let Some(Value::String(s)) = map.get(key)
        && let Ok(parsed) = serde_json::from_str::<Value>(s)
    {
        map.insert(key.to_string(), parsed);
    }
}

#[cfg(feature = "for-server")]
pub fn rename_key(map: &mut Map<String, Value>, old_key: &str, new_key: &str) {
    if let Some(v) = map.remove(old_key) {
        map.insert(new_key.to_string(), v);
    }
}

#[cfg(feature = "for-server")]
pub fn rename_and_fix_json(map: &mut Map<String, Value>, old_key: &str, new_key: &str) {
    // 同时完成：取出旧值 -> (如果是 String 则解析) -> 插入新 Key
    if let Some(mut value) = map.remove(old_key) {
        if let Value::String(s) = &value
            && let Ok(parsed) = serde_json::from_str::<Value>(s)
        {
            value = parsed;
        }
        map.insert(new_key.to_string(), value);
    }
}
