//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "dynamic_cpu_per_core")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub dynamic_monitoring_id: i64,
    pub core_id: i64,
    #[sea_orm(column_type = "Double")]
    pub cpu_usage: f64,
    pub frequency_mhz: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dynamic_monitoring::Entity",
        from = "Column::DynamicMonitoringId",
        to = "super::dynamic_monitoring::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DynamicMonitoring,
}

impl Related<super::dynamic_monitoring::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicMonitoring.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
