//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "dynamic_monitoring")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub node_uuid: Uuid,
    pub time: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_cpu_usage: Option<f64>,
    pub total_memory: Option<i64>,
    pub available_memory: Option<i64>,
    pub used_memory: Option<i64>,
    pub total_swap: Option<i64>,
    pub used_swap: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub load_one: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub load_five: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub load_fifteen: Option<f64>,
    pub boot_time: Option<i64>,
    pub uptime: Option<i64>,
    pub process_count: Option<i64>,
    pub udp_connections: Option<i64>,
    pub tcp_connections: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dynamic_cpu_per_core::Entity")]
    DynamicCpuPerCore,
    #[sea_orm(has_many = "super::dynamic_disk::Entity")]
    DynamicDisk,
    #[sea_orm(has_many = "super::dynamic_network_interface::Entity")]
    DynamicNetworkInterface,
}

impl Related<super::dynamic_cpu_per_core::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicCpuPerCore.def()
    }
}

impl Related<super::dynamic_disk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicDisk.def()
    }
}

impl Related<super::dynamic_network_interface::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicNetworkInterface.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
