//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dynamic_disk")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub dynamic_monitoring_id: i64,
    pub kind: String,
    pub name: String,
    pub file_system: Option<String>,
    pub mount_point: String,
    pub total_space: Option<i64>,
    pub available_space: Option<i64>,
    pub is_removable: bool,
    pub is_read_only: bool,
    pub read_speed: Option<i64>,
    pub write_speed: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dynamic_monitoring::Entity",
        from = "Column::DynamicMonitoringId",
        to = "super::dynamic_monitoring::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DynamicMonitoring,
}

impl Related<super::dynamic_monitoring::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicMonitoring.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
