//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod dynamic_cpu_per_core;
pub mod dynamic_disk;
pub mod dynamic_monitoring;
pub mod dynamic_network_interface;
pub mod static_cpu_per_core;
pub mod static_monitoring;
