//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::dynamic_cpu_per_core::Entity as DynamicCpuPerCore;
pub use super::dynamic_disk::Entity as DynamicDisk;
pub use super::dynamic_monitoring::Entity as DynamicMonitoring;
pub use super::dynamic_network_interface::Entity as DynamicNetworkInterface;
pub use super::static_cpu_per_core::Entity as StaticCpuPerCore;
pub use super::static_monitoring::Entity as StaticMonitoring;
