//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "static_monitoring")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub node_uuid: Uuid,
    pub time: i64,
    pub physical_cores: Option<i64>,
    pub logical_cores: Option<i64>,
    pub system_name: Option<String>,
    pub system_kernel: Option<String>,
    pub system_kernel_version: Option<String>,
    pub system_os_version: Option<String>,
    pub system_os_long_version: Option<String>,
    pub distribution_id: Option<String>,
    pub system_host_name: Option<String>,
    pub arch: Option<String>,
    pub virtualization: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::static_cpu_per_core::Entity")]
    StaticCpuPerCore,
}

impl Related<super::static_cpu_per_core::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaticCpuPerCore.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
