//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "static_cpu_per_core")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub static_monitoring_id: i64,
    pub core_id: i64,
    pub core_name: String,
    pub vendor_id: Option<String>,
    pub brand: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::static_monitoring::Entity",
        from = "Column::StaticMonitoringId",
        to = "super::static_monitoring::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StaticMonitoring,
}

impl Related<super::static_monitoring::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StaticMonitoring.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
