name: nodeget-agent-ci

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "docs/**"
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Agent Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-system
        with:
          toolchain: nightly
          components: clippy

      - name: Cargo clippy
        working-directory: ./agent
        run: cargo clippy --profile minimal

  check:
    name: Agent Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-system
        with:
          toolchain: nightly
          components: clippy

      - name: Cargo clippy
        working-directory: ./agent
        run: cargo clippy --profile minimal